config/routes.rb
Rails.application.routes.draw do

  #mise en place du root principal
  root to:'pages#home' 

  #mise en place d'une page team depuis le controller pages
  get '/team', to: 'pages#team', as: 'team' #création d'un nom pour le chemin

  #mise en place d'une page contact depuis le controller pages
  get '/contact', to: 'pages#contact', as: 'contact' #création d'un nom pour le chemin

  #mise en place d'une route dynamique
  get 'welcome(/:first_name)', to: 'pages#welcome', as: 'welcome' #création d'un nom pour le chemin
  #mise en place d'un parametre optionnel pour first_name

  #mise en place d'un route dynamique
  get 'potin/:id', to:'pages#potin', as: 'potin'

  #mise en place d'un route dynamique
  get 'potin/author/:title', to:'pages#author', as: 'author'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  has_many :tags, through: :gossips
  
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :zip_code, presence: true, length: { is: 5 }, format: { with: /\A\d{5}\z/, message: 'Zip code should be in the format 12345' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable

  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :content, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  
  validates :title, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :private_messages_sent, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :private_messages_received, class_name: 'PrivateMessage', foreign_key: 'recipient_id'
  has_many :comments
  has_many :likes

  validates :first_name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 13 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    #définition de la page home
      def home
        puts params.inspect
        @gossips = Gossip.all
      end
    
    #définition de la page team
      def team
        
      end
    
    #définition de la page contact
      def contact
        
      end
    
    #définition de la page welcome dynamique
      def welcome
        @first_name = params[:first_name]
        puts params[:first_name].inspect
      end
    
    #définition de la page potin dynamique
      def potin
        @gossips = Gossip.all
        @id = params[:id]
      end
    
    
    #définition de la page auteur dynamique
    def author
      @gossips = Gossip.all
      @title = params[:title]
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css' %>
  </head>

  <body>
    <div class="container-fluid">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="<%= root_path %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <span class="fs-4" style="color:#ff60aa; font-weight: 900">The Gossip Project</span>
        </a>

        <ul class="nav nav-pills">
          <li class="nav-item"><a href="<%= root_path %>" class="nav-link active" aria-current="page">Accueil</a></li>
          <li class="nav-item"><a href="<%= team_path %>" class="nav-link">Team</a></li>
          <li class="nav-item"><a href="<%= contact_path %>" class="nav-link">Contact</a></li>
        </ul>
      </header>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/author.html.erb
<div class="container" style="height:80vh">
  <h1>Profil de <span style="#ff60aa"><%= @title%></span></h1>
  <h3 class="mb-5">Ses ragots :</h3>

  <div class="container row justify-content-center">
    <% @gossips.each do |gossip| %>
      <% if gossip.title == @title%>
        <div class="card mb-3 mx-4 card-home" style="width: 18rem;">
          <div class="card-body">
            <p class="card-text"><em><%= gossip.content %></em></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <a href="<%= root_path %>" class="btn-auteur btn btn-danger mt-3 rounded-pill">Revenir au menu</a>
</div>

app/views/pages/contact.html.erb
<div class="container contact " style="height:80vh">
	<div class="row">
		<div class="col-md-3">
			<div class="contact-info">
				<img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
				<h3>Contactez-nous,</h3>
				<h4>remplissez le formulaire</h4>
			</div>
		</div>
		<div class="col-md-9">
			<div class="contact-form">
				<div class="form-group">
				  <label class="control-label col-sm-2" for="fname">Prénom :</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="fname" placeholder="Tape ici ton prénom" name="fname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="lname">Nom:</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control" id="lname" placeholder="Tape ici ton nom" name="lname">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="email">Email:</label>
				  <div class="col-sm-10">
					<input type="email" class="form-control" id="email" placeholder="Tape ici ton mail" name="email">
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="comment">Commentaire:</label>
				  <div class="col-sm-10">
					<textarea class="form-control" rows="5" id="comment" placeholder="Tape ici ton commentaire"></textarea>
				  </div>
				</div>
				<div class="form-group">        
				  <div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-default">Envoyer</button>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<h1 class="row justify-content-center mb-5"> Bienvenue sur The Gossip Project</h1>
<h3 class="row justify-content-center mb-5" style="color:#ff60aa ">Les derniers ragots en vogue ↓</h3>


<div class="container row justify-content-center">
<% @gossips.each do |gossip| %>

<div class="card mb-3 mx-2 card-home" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= gossip.title %></h5>
    <p class="card-text"><em><%= gossip.content %></em></p>
    <a href="potin/<%=gossip.id%>" class="btn" style="color:#ff60aa">Voir les détails</a>
  </div>
</div>
<% end %>
</div>

app/views/pages/potin.html.erb
<div class="container" style="height:80vh">
    <% @gossips.each do |gossip| %>
      <% if gossip.id == @id.to_i%>
        <h3> <%= gossip.title %></h3>
        <p> <em><%= gossip.content %></em></p>
        <a href="<%= root_path %>" class="btn btn-danger m-3 rounded-pill">👈 Revenir au menu</a>
        <a href="author/<%= gossip.title%>" class="btn-auteur btn btn-danger m-3 rounded-pill">Profil de l'auteur</a>
        <hr>
      <% end %>
    <% end %>
</div>

app/views/pages/team.html.erb
<div class="py-5 team4">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <div class="col-md-6 text-center">
        <h1 class="mb-3">Les membres de l'équipe</h1>
        <h6 class="subtitle">Il n'y a que moi.</h6>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-12 text-center pt-2">
        <div class="row">
          <h5 class="mt-4 font-weight-medium mb-0">Tommy RISCHMANN</h5>
        </div>
      </div>
    </div>
  </div>
</div>